### ISSUE TITLE
Disable attachments and audio recording?

### ISSUE THREAD

**Issue by rnaud** [exyte/Chat#100]
I can't seem to find this in the documentation. 

Is there a way to disable everything but text in the setup?

**Comment by gzlboy** [comment]
you can see the enum in this：
`public enum AvailableInputType {
    case full // media + text + audio
    case textAndMedia
    case textAndAudio
    case textOnly
`
and use this modifier:
`
ChatView(messages: chatVM.messages, recorderSetting: recorderSetting) { draft in
            
        }
        .setAvailableInput(.textOnly)
`

**Comment by rnaud** [comment]
Thank you!
