### ISSUE TITLE
 How to implement dynamic message?

### ISSUE THREAD

**Issue by gzlboy** [exyte/Chat#104]
I use exyteChat as the view for AI chat, and the AI ​​API returns answers through server-side events. This means that message need to be combined dynamically(spliced ​​text). 
Currently, exyteChat uses `@Published var messages:[Message]` to observe changes in messages and update the view. Directly modifying the text of the message does not trigger a view update. How should I modify it to achieve this requirement?

Have a nice day!
Thanks！

**Comment by xiongxiongjiang** [comment]
me too
