### ISSUE TITLE
Sheet dismiss issue

### ISSUE THREAD

**Issue by Dave181295** [exyte/Chat#108]
When adding the ChatView in a `.sheet` modifier, the dismiss gesture is reversed.. (from top to bottom)

iOS 17

**Comment by f3dm76** [comment]
I didn't really understand the problem. Unfortunately we do not have time for open source right now, but if you think this can be fixed from the lib's side, you are most welcome to support this library by submitting a PR. Have a nice day

**Comment by Dave181295** [comment]
Please try adding the `ChatView`inside a `.sheet()` you'll see you can only dismiss the sheet with a gesture from bottom to top.
