### ISSUE TITLE
Can't seem to get SPM working

### ISSUE THREAD

**Issue by mightyleader** [exyte/Chat#22]
![Screenshot 2023-07-05 at 15 55 11](https://github.com/exyte/Chat/assets/1516552/6040afe0-ec18-42c0-9cfd-564065ae966e)

As per screenshot, integration with Xcode SPM not working. Other packages working as expected.

**Comment by mightyleader** [comment]
Works if I specify the main branch rather than the current version 1.0.0

**Comment by f3dm76** [comment]
Hey @mightyleader, the issue was somehow because Chat used master branch of its dependency library. I switched to fixed version and now it works. Please check out version 1.0.3. Have a wonderful day!
