### ISSUE TITLE
message are at the bottom but I want to move them to the top

### ISSUE THREAD

**Issue by pprevalon1** [exyte/Chat#29]
How can I push the list of messages all the way up when I don't have much message

<img width="339" alt="image" src="https://github.com/exyte/Chat/assets/128199596/0c4fc9c3-4c93-416c-978c-48a496325e16">

**Comment by f3dm76** [comment]
Hey @pprevalon1, seeing as to how you have a custom InputField view, I think you can insert a Spacer there, please give it a go, have a nice day

**Comment by quantappm** [comment]
Hi @f3dm76 inserting a Spacer() between UIList and the custom InputField view doesn't work for me. Do you have solution for this ?

**Comment by f3dm76** [comment]
Sorry @quantappm, the default chat behaviour, like in most popular chats, is staying at the bottom. This library doesn't support your use case. I'll let you know if that changes in the future
