### ISSUE TITLE
Custom InputView dismissing keyboard when chat view is tapped

### ISSUE THREAD

**Issue by bennettl** [exyte/Chat#33]
Using the example to build my own custom input view, I'm having a hard time understanding how I would dismiss the keyboard when the user taps on the chat view

I notice the internal implementation of the ChatView has

```
 @StateObject private var globalFocusState = GlobalFocusState()
.environmentObject(globalFocusState)
```

but that is not something I can access inside `inputViewBuilder`. I tried defining my own

```
@FocusState private var isChatFocus: Bool
```

but i don't have a handler to use to dismiss it when the user taps on the chat view. I tried `onTapGesture` on the chat view, but it doesn't fire.

```
ChatView(messages: viewModel.messages) { draft in
    viewModel.send(draft: draft)
} inputViewBuilder: { textBinding, attachments, state, style, actionClosure in
    Group {
        switch style {
        case .message: // input view on chat screen
            VStack {
                HStack {
                    Button("Send") { actionClosure(.send) }
                    Button("Attach") { actionClosure(.photo) }
                }
                TextField("Write your message", text: textBinding)
            }
        case .signature: // input view on photo selection screen
            VStack {
                HStack {
                    Button("Send") { actionClosure(.send) }
                }
                TextField("Compose a signature for photo", text: textBinding)
                    .background(Color.green)
            }
        }
    }
}```

**Comment by 2brandonh** [comment]
Taking a look at the existing code, it looks like there already exists an @FocusState that keeps track of the uid currently being focused, which determines whether the keyboard is displayed or hidden.

`import SwiftUI

struct TextInputView: View {

    @Environment(\.chatTheme) private var theme

    @EnvironmentObject private var globalFocusState: GlobalFocusState

    @Binding var text: String
    var inputFieldId: UUID
    var style: InputViewStyle

    var body: some View {
        TextField("", text: $text, axis: .vertical)
            .customFocus($globalFocusState.focus, equals: .uuid(inputFieldId))
            .placeholder(when: text.isEmpty) {
                Text(style.placeholder)
                    .foregroundColor(theme.colors.buttonBackground)
            }
            .foregroundColor(style == .message ? theme.colors.textLightContext : theme.colors.textDarkContext)
            .padding(.vertical, 10)
            .onTapGesture {
                globalFocusState.focus = .uuid(inputFieldId)
            }
    }
}`

This is from the default input view _TextInputView.swift_, and shows that when the text field is tapped, the globalFocusState.focus is set toward its corresponding uid. And in the root body of code, _ChatView.swift_, whenever the user taps elsewhere, the globalFocusState.focus is set to nil (hiding the keyboard).

I think if you build your custom input around the existing globalFocusState.focus in the project, your custom implementation should be able to work.

**Comment by bennettl** [comment]
Thanks @2brandonh !!! Looks like it can work, the problem i have is that a lot of the internals are not visible outside the module (e.g. the GlobalFocusState has a default internal access modifier), so I'm kind of limited with what I have to work with provided by the closure. 

```
final class GlobalFocusState: ObservableObject {
    @Published var focus: Focusable?
}
```

May need to fork this or download it as a local repository to open up the visibility level

**Comment by f3dm76** [comment]
Hey @bennettl @2brandonh, I've added `dismissKeyboardClosure` into `inputViewBuilder`, I hope that helps. Please let me know if you have any other mechanism of keyboard dismissing you'd like me to implement. You can also use this `UIApplication.shared.sendAction(#selector(UIResponder.resignFirstResponder), to: nil, from: nil, for: nil)` if you can use UIKit in your projects

**Comment by spartan-kienhoang** [comment]
Hi @f3dm76 
I hope you are doing well.

I have a `ChatView` with custom `Message` and `InputView`. 
How can I do something like tapping around to dismiss the keyboard?
