### ISSUE TITLE
Allow customizing the media picker mode

### ISSUE THREAD

**Issue by ferranconde** [exyte/Chat#36]
Hi! First of all, thanks for open-sourcing this package!

I would like to customize the media types selectable in the media picker (only photos / only videos / both). 
I am aware that `ExyteMediaPicker` allows defining a `mediaSelectionType`. However, if I understand correctly, `ExyteChat` only exposes the `mediaSelectionLimit` property of the underlying `ExyteMediaPicker` via an `assetsPickerLimit` modifier; the `mediaSelectionType` property is not exposed.

Is there a way for me to customize the media selection type directly from `ExyteChat`?
Thank you!

**Comment by f3dm76** [comment]
Hey @ferranconde, I've added the ability to pass `mediaPickerSelectionParameters` to a chat, same as to MediaPicker itself, please check out version 1.2.1. Have a fantastic day!
