### ISSUE TITLE
Load more Crash 

### ISSUE THREAD

**Issue by vledly** [exyte/Chat#37]
After adding new items into `@Published var messages: [Message] = []` get a crash :( 
When add only 1 item it works fine.

`*** Assertion failure in -[UITableView _Bug_Detected_In_Client_Of_UITableView_Invalid_Number_Of_Rows_In_Section:], UITableView.m:2 611
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (40) must be equal to the number of rows contained in that section before the update (20), plus or minus the number of rows inserted or deleted from that section (12 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out). Table view: <UITableView: 0x11a12ee00; frame = (-3.12915e-14 0; 393 662.333); transform = [-1, 1.2246467991473532e-16, -1.2246467991473532e-16, -1, 0, 0]; clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x600000d573f0>; backgroundColor = UIExtendedSRGBColorSpace 1 1 1 1; layer = <CALayer: 0x600000324c00>; contentOffset: {0, 985.66666666666663}; contentSize: {392.99999999999994, 1648.1000495910644}; adjustedContentInset: {1.4210854715202004e-14, 0, 0, 0}; dataSource: <_TtGCV9ExyteChat6UIList11CoordinatorV8Futurest15ChatMessageView__: 0x60000330b0c0>>'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001804658a8 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000018005c09c objc_exception_throw + 56
	2   Foundation                          0x0000000180cf3a5c _userInfoForFileAndLine + 0
	3   UIKitCore                           0x000000011522f8f0 -[UITableView _Bug_Detected_In_Client_Of_UITableView_Invalid_Number_Of_Rows_In_Section:] + 92
	4   UIKitCore                           0x000000011522f14c -[UITableView _endCellAnimationsWithContext:] + 9676
	5   UIKitCore                           0x00000001152430b0 -[UITableView endUpdatesWithContext:] + 128
	6   Futurest                            0x00000001014112ac $s9ExyteChat6UIListV12updateUIView_7contextySo11UITableViewC_7SwiftUI0E20RepresentableContextVyACyxGGtFyyYbcfU_yyXEfU2_ + 1000
	7   Futurest                            0x000000010140fcec $sIg_Ieg_TR + 20
	8   Futurest                            0x000000010140fd10 $sIeg_IyB_TR + 24
	9   libdispatch.dylib                   0x00000001045cd93c _dispatch_client_callout + 16
	10  libdispatch.dylib                   0x00000001045de80c _dispatch_async_and_wait_invoke + 192
	11  libdispatch.dylib                   0x00000001045cd93c _dispatch_client_callout + 16
	12  libdispatch.dylib                   0x00000001045dd5e4 _dispatch_main_queue_drain + 1228
	13  libdispatch.dylib                   0x00000001045dd108 _dispatch_main_queue_callback_4CF + 40
	14  CoreFoundation                      0x00000001803c61b4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
	15  CoreFoundation                      0x00000001803c08cc __CFRunLoopRun + 1936
	16  CoreFoundation                      0x00000001803bfd28 CFRunLoopRunSpecific + 572
	17  GraphicsServices                    0x000000018986ebc0 GSEventRunModal + 160
	18  UIKitCore                           0x0000000115033fdc -[UIApplication _run] + 868
	19  UIKitCore                           0x0000000115037c54 UIApplicationMain + 124
	20  SwiftUI                             0x000000010ba40524 OUTLINED_FUNCTION_70 + 500
	21  SwiftUI                             0x000000010ba403c4 OUTLINED_FUNCTION_70 + 148
	22  SwiftUI                             0x000000010b752108 OUTLINED_FUNCTION_2 + 92
	23  Futurest                            0x0000000100fd5bc8 $s8Futurest0A3AppV5$mainyyFZ + 40
	24  Futurest                            0x0000000100fd6040 main + 12
	25  dyld                                0x0000000103451558 start_sim + 20
	26  ???                                 0x0000000102f52058 0x0 + 4344586328
	27  ???                                 0x0215000000000000 0x0 + 150026162586779648
)
libc++abi: terminating due to uncaught exception of type NSException`

**Comment by f3dm76** [comment]
Hey @vledly, thank you for bringing this to our attention, please try version 1.2.2, should be fixed there, have a wonderful day!

**Comment by vledly** [comment]
@f3dm76 спасибо!)
