### ISSUE TITLE
Crash when launching chat due to lack of NSPhotoLibraryUsageDescription

### ISSUE THREAD

**Issue by alanscarpa** [exyte/Chat#46]
Is there a way to only allow text as a message type? My app doesn't intend to send photos and I'd prefer not to fill out a `NSPhotoLibraryUsageDescription` since it really isn't needed.

As a suggestion - it may be helpful to first time users to outline what Privacy descriptions they may need so they can avoid the crash as well.

**Comment by f3dm76** [comment]
Hey @alanscarpa, valid point and a good idea. I'll see what I can do as soon as I have time. Have a wonderful day!

**Comment by alanscarpa** [comment]
@f3dm76 Just to follow up - is there a way to limit users to only using text in the message? Is it just a matter of customizing the input bar?

**Comment by f3dm76** [comment]
A matter of customizing the input bar
