### ISSUE TITLE
Reply Menu Issues

### ISSUE THREAD

**Issue by mwurm293** [exyte/Chat#47]
1. the Reply btn on long press is hidden by the message that is long pressed when the message is >2 lines long
2. tapping the Reply btn doesnt actually change anything in the UI that I can tell. 

Is there a way to turn off the long press?

**Comment by f3dm76** [comment]
Hey @mwurm293, thank you for bringing this to our attention. I didn't see the second issue on main branch, but I did fix the first one. I also added a modifier to turn it off showMessageMenuOnLongPress. Please check out version 1.3.2, have a great day!

**Comment by mwurm293** [comment]
wow that was fast on #1 ! thank you.

On #2, i guess im just not seeing whats different after selecting reply in the contextmenu. in iMessage it creates that circuit trace through the replied messages, but i dont see that here.
