### ISSUE TITLE
Can't load any icons when using cocoapod

### ISSUE THREAD

**Issue by hoaknoppix** [exyte/Chat#49]
I am trying this repo with cocoapod for my project, however, there is no icon loaded in the chatview, I also double check the pod source and it seems the media resource was missing. Did we miss that on pod repo or I miss something? Thank you.

**Comment by f3dm76** [comment]
Hey @hoaknoppix, thanks for bringing this to our attention, could you please check out version 1.3.4 - should be fixed there. Have a great day!

**Comment by hoaknoppix** [comment]
Thanks for your quick response. It fixed. Thank you!!!!
