### ISSUE TITLE
Configuration mode to eliminate attachments and camera?

### ISSUE THREAD

**Issue by rnewman** [exyte/Chat#53]
I don't see a way to push a `ChatView` into a text-only or text-and-audio-only mode. Is this a reasonable feature request, or am I missing something?

**Comment by f3dm76** [comment]
Hey @rnewman, seems like a rather unusual request. You could pass your own input view builder without image adding button to achieve this. But if more people need it, I'll consider adding this if I have time. Have a nice day

**Comment by rnewman** [comment]
Got it — thanks for the quick response!

**Comment by f3dm76** [comment]
Hey @rnewman, we've added this feature in version 1.3.7, you are most welcome to check it out. Have a nice day

**Comment by gzlboy** [comment]
That's awesome! I need this feature!
