### ISSUE TITLE
How to build a first sample message

### ISSUE THREAD

**Issue by alexe100** [exyte/Chat#55]
Hello
I am trying to use exyte chat for the first time but without success. In the most simple code:

@State var messages: [Message] = []

var body: some View {
    ChatView(messages: messages) { draft in
        //yourViewModel.send(draft: draft)
    }
}

how can I initialize the messages array with a first sample message to be displayed when the screen first appears?
I am trying to use onAppear() to just append a simple and sample message but it is being hard to initialize it. Could you provide what to pass the the append call?

Thank you

**Comment by f3dm76** [comment]
Hey @alexe100, there are 2 working example in the repository, please refer to them

**Comment by alexe100** [comment]
I did but for beginners it is not an easy way and a "hello world" sample would be great.
Thank you any way.
