### ISSUE TITLE
Internal Inconsistency crash

### ISSUE THREAD

**Issue by johnauger** [exyte/Chat#56]
Hi

I'm seeing occurrences of the NSInternalInconsistencyException crash, that seems to have been an issue for other users in the past based on closed issues:

`Fatal Exception: NSInternalInconsistencyException
Invalid batch updates detected: the number of sections and/or rows returned by the data source before and after performing the batch updates are inconsistent with the updates. Data source before updates = { 1 section with row counts: [3] } Data source after updates = { 1 section with row counts: [0] } Updates = [ Delete row (0 - 1), Delete row (0 - 0) ] `

Crash coming from UIList.swift, line 104 as it attempts to `performBatchUpdates`.

I've not been able to replicate in testing as yet, but getting regular reports of the crash from our production release.

Any advice welcome... Thanks.

**Comment by johnauger** [comment]
Am running version 1.3.5 of the framework

**Comment by f3dm76** [comment]
Hey @johnauger, I understand that this is a serious issue but I really cannot help you unless I have a working reproducible example. From your end you can uncomment the print statements in UIList file to help track down the issue, they spell out every step of a UITableView updating. It could be a problem with the messages with same ids being updated in an unexpectable fashion, meaning that the `isEqual` method of a message is not considering your change an actual change, but that is just a guess.

**Comment by johnauger** [comment]
Thanks, yeah - I figured it'd be hard to do much without replicable code but as it all works fine in my own testing I'm drawing a blank... Will check out your suggestion about IDs and do some more debugging myself. Will update if I find anything more concrete.
