### ISSUE TITLE
MessageTime isn't themed

### ISSUE THREAD

**Issue by rnewman** [exyte/Chat#58]
https://github.com/exyte/Chat/blob/main/Sources/ExyteChat/ChatView/MessageView/MessageTimeView.swift#L15

```swift
    var body: some View {
        Text(text)
            .font(.caption)
            .foregroundColor(isCurrentUser ? .white : .black)
            .opacity(0.4)
    }
```

I think these should be pulling from one of the theme colors.

There are some other instances in the rest of that file.

**Comment by f3dm76** [comment]
Hey @rnewman, please check out version 1.3.7 - should be fixed there. Have a great day!
