### ISSUE TITLE
CameraStubView not closed when tapped on "Close" button

### ISSUE THREAD

**Issue by mixtly87** [exyte/Chat#59]
1. Run the app in the Simulator.
2. Tap the Camera button in text input view
3. CameraStubView is presented with Close button
4. Tap the Close button. Nothing happens.

Expected: CameraStubView should be closed when tapped on Close button

**Comment by f3dm76** [comment]
Hey @mixtly87, please force update packages - ExyteMediaPicker should be 2.2.3, everything works as expected on that version
