### ISSUE TITLE
Notifications?

### ISSUE THREAD

**Issue by brazill7** [exyte/Chat#68]
Does this natively support push notifications on new messages?

**Comment by f3dm76** [comment]
Hello @brazill7, what do you mean? Like displaying system notification popups?

**Comment by brazill7** [comment]
Like push notifications, so if you receive a message you'd also get a notification

**Comment by f3dm76** [comment]
Apple's push notifications - APNS (Apple Push Notification Service) - are setup by the app in AppDelegate, and you'll need your custom back end to implement them. What would you like this library to do?
