### ISSUE TITLE
Can i limit audio duration, such as 60s?

### ISSUE THREAD

**Issue by gzlboy** [exyte/Chat#71]
Users can record for up to 60 seconds
Thanks!

**Comment by f3dm76** [comment]
Hey @gzlboy, please pass your custom inputViewBuilder closure - you can achieve anything by doing that. Please refer to example project and readme file for how to pass inputViewBuilder instructions, InputViewAction should have everything you need to record an audio and the limitations implementation is up to you. Have a nice day

**Comment by gzlboy** [comment]
Thanks Reply!
I will try later~~
