### ISSUE TITLE
Seeking Advice: How to Add 'message response buttons' to a message

### ISSUE THREAD

**Issue by jkanalakis** [exyte/Chat#72]
I'm seeking some advice regarding how I should go about adding message response buttons like we see in WhatsApp and other messaging platforms. They display convenient short answer options in a chat message as shown in the attachment. Any suggestions where I should start for implementing this capability? There can be limitations, such as a max of 3 buttons, and pressing the button only fills in the draft message and automatically sends the message. I would appreciate any thoughts about where to get started and which classes should be extended.

<img width="297" alt="message-buttons" src="https://github.com/exyte/Chat/assets/1013013/76fa4545-f851-4ef1-a899-26d73f449e74">

**Comment by f3dm76** [comment]
Hey @jkanalakis , I am working on this and many other features in comments-chat-type branch. You are most welcome to try and use it. On this branch there is a closure returning DefaultMessageMenuAction in MessageBuilderClosure - and .reply is the action

`func messageCell(_ message: Message, _ commentsPosition: CommentsPosition?, showMenuClosure: @escaping ()->(), actionClosure: @escaping (Message, DefaultMessageMenuAction) -> Void, attachmentClosure: @escaping (Attachment) -> Void) -> some View {
<...>
Group {
    Image(.postComment)
        .foreground(.appGreyMedium)
    Text("Reply")
}
.onTapGesture {
    inputKeyboardFocus = true
    actionClosure(message, .reply)
}
`
Please remember it's a work in progress. Have a great day!

**Comment by f3dm76** [comment]
This update is now part of release 2.0.1, please check it out. Have a wonderful day!

**Comment by jkanalakis** [comment]
Hi Alisa,

Thank you for the note. I'm very excited to use it. But I was not able to get it working. Is there a working sample implementation that I can reference?

John K.

**Comment by gittoday** [comment]
@jkanalakis  Let me know if you find a way to make it work.
