### ISSUE TITLE
"Today" and "Yesterday" upside down when building example project

### ISSUE THREAD

**Issue by deanthing** [exyte/Chat#79]
I noticed that the "today" and "yesterday" indicators for a group of messages is displayed upside down.

Tested on iPhone15 and iOS 17 and 17.4

![Screenshot 2024-07-16 at 5 57 28 PM](https://github.com/user-attachments/assets/5ddaa6b9-3d4c-4bb6-b84c-81d4b327c484)
![Screenshot 2024-07-16 at 5 57 33 PM](https://github.com/user-attachments/assets/085ac304-da3b-4c87-a7bb-0772e623d241)

**Comment by deanthing** [comment]
`.rotationEffect(Angle(degrees: (type == .conversation ? 180 : 0)))`

Why does the chat type affect if the date is rotated? I

Great library btw. Thanks

**Comment by thebarndog** [comment]
Also experiencing this

**Comment by seanadhik50** [comment]
Have the same issue

**Comment by f3dm76** [comment]
Hey guys, please check out version 2.0.3. Have a great day!
