### ISSUE TITLE
How can i set the recorder SampleRate?

### ISSUE THREAD

**Issue by gzlboy** [exyte/Chat#92]
I use an AI service to convert audio to text. The service limits the sampling rate of the audio to 16000 Hz, and the sampling number is 16-bit audio. Is there any property that can be set?

**Comment by f3dm76** [comment]
Hey @gzlboy, no, currently there isn't. Unfortunately we do not have time for open source right now. You are most welcome to support this library by submitting a PR adding this functionality. Have a nice day

**Comment by gzlboy** [comment]
I have

> Hey @gzlboy, no, currently there isn't. Unfortunately we do not have time for open source right now. You are most welcome to support this library by submitting a PR adding this functionality. Have a nice day

Hi,I have pushed a PR, please check it:)

**Comment by f3dm76** [comment]
All merged
